### ISSUE TITLE
Compile to HTML

### ISSUE THREAD

**Issue by lukasoppermann** [sindresorhus/gulp-dust#16]
Hey,

I would love to see an option to compile to html instead of js. What do you thing @sindresorhus would you be in for this? I could try to send a PR.

**Comment by sindresorhus** [comment]
I'm open do a good PR with tests and docs. Could be `dust.render([options])`.

**Comment by lukasoppermann** [comment]
Hey, I am currently very busy, but I hope I will be able to get started with this next week.

**Comment by lukasoppermann** [comment]
Hey, @sindresorhus are you sure about `dust.render([options])`? Because this would mean basically a totally separate function from the main `dust` function, correct?

Shouldn't we rather have a new option `outputType: html` by default it would be `outputType: js`. This way we could potentially support more options in the future, if needed.

**Comment by sindresorhus** [comment]
The reason for separate functions is that rendering requires data, while precompiling does not. Then we would have a `data` option that only applies when `outputType: html`. This makes for not so good API. Better to keep them separate.

> This way we could potentially support more options in the future, if needed.

It's dangerous to optimize for imaginary future use-cases.

**Comment by lukasoppermann** [comment]
Its not really optimizing for future use cases, but I definitely see your other point.

**Comment by sindresorhus** [comment]
Dust is no longer maintained.
