### ISSUE TITLE
How to pass options like amd feature, cwd to gulp-dust task?

### ISSUE THREAD

**Issue by bharanidharan-k** [sindresorhus/gulp-dust#6]
As I understand there is a feature of passing name and preserveWhiteSpace in gulp-dust, what about the support for various other options like amd, cwd?

**Comment by kevva** [comment]
Can you give an example of this in the Dust API?

**Comment by bharanidharan-k** [comment]
For Eg, I can use "dustc --amd myTemplate.dust -o output.js" in command line to compile a dust into amd supported module. However, If I have to achieve similar in using gulp-dust, How will I be able to do it. You can refer my question with code snippet example here 

http://stackoverflow.com/questions/30575955/passing-dust-compilation-options-to-gulp-dust-task

**Comment by kevva** [comment]
I don't see how you would do this in node?

**Comment by bharanidharan-k** [comment]
I've just fixed and raised a pull request. Can you please merge it with master?
